version: '3.4'

services:
  transferbridge:
    image: ${DOCKER_REGISTRY-}transferbridge
    build:
      context: .
      dockerfile: TransferBridge/Dockerfile
    environment:
      RabbitMQ__Publisher__HostName: rabbitmq
      RabbitMQ__Publisher__UserName: user
      RabbitMQ__Publisher__Password: password
    networks:
        - transfer_bridge_network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - transfer_bridge_network
networks:
  transfer_bridge_network:
    driver: bridge
